version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  test_and_lint:
    executor: node/default
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Lint code
          command: yarn lint
      - run:
          name: Test code
          command: yarn test
      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - '16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48'
            - '9f:10:3c:f2:df:f4:93:d8:e7:b0:14:0e:42:74:8f:66'
      - run:
          name: Authenticate NPM registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish NPM package
          command: npm run deploy
      - run:
          name: Configure GitHub information
          command: |
            git config --global user.email "${GH_EMAIL}"
            git config --global user.name "${GH_NAME}"
      - run:
          name: Deploy documentation
          command: scripts/deploy-docs.sh

workflows:
  build-and-deploy:
    jobs:
      - test_and_lint:
          filters:
            tags:
              only: /^v[0-9]+.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+.*/
            branches:
              ignore: /.*/
